apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
spec:
  replicas: {{ .Values.result.replicaCount }}
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
        - name: result
          image: "{{ .Values.result.image }}:{{ .Values.result.tag }}"
          ports:
            - containerPort: 80
          env:
            - name: POSTGRES_HOST
              value: db