apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
spec:
  revisionHistoryLimit: 3
  replicas: {{ .Values.vote.replicaCount }}
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
        prometheus.io/path: "/metrics"
        fluentd.io/parser: "json"
        fluentd.io/tag: "vote-app"   
    spec:
      containers:
        - name: vote
          image: "{{ .Values.vote.image }}:{{ .Values.vote.tag }}"
          ports:
            - containerPort: 80
          env:
            - name: REDIS_HOST
              value: redis
