vote:
  image: dockersamples/examplevotingapp_vote
  tag: latest
  replicaCount: 1
vote-image: quang47/example-voting-app_vote:ddc3d588
vote-tag: ddc3d588


result:
  image: dockersamples/examplevotingapp_result
  tag: latest
  replicaCount: 1

worker:
  image: dockersamples/examplevotingapp_worker
  tag: latest
  replicaCount: 1

redis:
  image: redis
  tag: alpine

db:
  image: postgres
  tag: 15-alpine
  postgresUser: postgres
  postgresPassword: postgres
  persistence:
    enabled: true
    size: 1Gi